name: Run C# Program

on:
  push:
    branches:
      - main  # 当你推送到 main 分支时触发
      - feature/python_use
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 运行环境

    steps:
      # 第一步：检出你的代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 第二步：设置 .NET SDK（自动下载指定版本，比如 8.0.x 或 7.0.x）
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip

      # 第五步：运行程序（比如控制台应用）
      - name: Run the C# program
        run: dotnet run --project ./ActionTest/ActionTest.csproj
